/* Rasterize selected SVG outputs offline; no browser or original-site request. */
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'..'),out=process.argv[2],sharp=require(path.join(process.argv[3],'sharp'));
if(!out)throw Error('Output directory required');fs.mkdirSync(out,{recursive:true});
const ctx=vm.createContext({window:{},console});for(const n of ['charts','momentum-highs','analysis-charts','network-views','relation-views','overview-views','research-notes','geo-views','earnings-views','ownership-views','satellite-views'])vm.runInContext(fs.readFileSync(path.join(root,'docs',n+'.js'),'utf8'),ctx);
const data=n=>JSON.parse(fs.readFileSync(path.join(root,'docs/data',n+'.json'),'utf8')),A=ctx.window.AnalysisCharts,G=ctx.window.NetworkViews;
const styles='<style>[hidden]{display:none}.axis{fill:#506d80;font-size:12px}.grid-line{stroke:#dce6ec;stroke-width:1}.reference-line{stroke:#93a8b6;stroke-width:1}.bar-name{fill:#274d66;font-size:13px}</style><rect width="100%" height="100%" fill="white"/>';
const samples={dynamics:A.surface(data('dynamics').sections[0].surface),risk:A.line(data('dynamics').sections[0].charts[0]),candles:A.candles(data('watch').sections[0]),forecast:A.forecast(data('ml').sections.find(s=>s.type==='ml')),growth:A.scatter3d(data('growth').sections[0]),globe:G.sphere(data('globe').sections[0],data('coastlines').arcs),network:G.graph(data('aragorn').sections[0])};
const priceCharts=ctx.window.ResearchCharts,rs=data('rs'),mom=data('momentum');
samples.rs_transport=priceCharts.line(rs.series.kr_transport,{kind:'rs',title:'운송 / KOSPI · 5Y z'});
samples.rs_us=priceCharts.line(rs.series.us_financials,{kind:'rs',title:'Financials / SPY · 5Y z'});
for(const n of [3,6])samples['momentum_'+n]=priceCharts.line(mom.curves.kr_transport[String(n)],{kind:'momentum',title:'운송 / KOSPI · '+n+'M'});
samples.rs_worst=priceCharts.bars(rs.stock_rankings.KR.weak.map(r=>({name:r.name,value:r.r1m})),{unit:'%',title:'1W 하위6종목 · 1M 수익률'});
for(const g of mom.new_highs.groups)if(g.rows.length)samples['new_high_'+g.market]=ctx.window.MomentumHighs.spark(g.rows[0]);
const sat=data('dragonglass').sections.find(s=>s.type==='satellite'),SV=ctx.window.SatelliteViews,sc={lon:0,lat:20,zoom:1,size:1,selected:'',mode:'rgb'};
samples.satellite_world=SV.map(sat,sc,data('coastlines').arcs);
const site=sat.sites.find(s=>s.id==='ST_BOISE'&&s.scene)||sat.sites.find(s=>s.scene);if(site)for(const mode of ['rgb','ndvi'])samples['satellite_'+mode]=SV.map(sat,{...SV.focus(sc,site),mode},data('coastlines').arcs).replace(/href="(data\/satellite\/[^\"]+\.png)"/g,(_,p)=>'href="data:image/png;base64,'+fs.readFileSync(path.join(root,'docs',p)).toString('base64')+'"');
samples.pead=A.scatter(data('strategies').sections.find(s=>s.group==='PEAD'&&s.type==='scatter'));
samples.reflex_hologram=A.hologram(data('regime').sections.find(s=>s.type==='hologram'));
samples.reflex_radar=A.radar(data('regime').sections.find(s=>s.type==='hologram'));
samples.pm_rates=A.line(data('pm_weekend').sections.find(s=>s.title==='미국 금리 분해 · 10Y'));
samples.pm_cta=A.line(data('pm_weekend').sections.find(s=>s.title==='CTA 시스템 추세 · 누적 자산배수'));
samples.gamma_profile=A.optionProfile(data('risk').sections.find(s=>s.type==='optionprofile'&&s.mode==='gamma'));
samples.oi_profile=A.optionProfile(data('risk').sections.find(s=>s.type==='optionprofile'&&s.mode==='oi'));
samples.rebalancing=A.rebalancing(data('risk').sections.find(s=>s.type==='rebalancing'));
samples.rebalancing_down=A.rebalancing(data('risk').sections.find(s=>s.type==='rebalancing'),-5);
samples.valuation_us=A.valuation(data('regime').sections.find(s=>s.type==='valuation').panels[0]);
samples.valuation_kr=A.valuation(data('regime').sections.find(s=>s.type==='valuation').panels[2],60);
samples.cftc=A.line(data('risk').sections.find(s=>s.group==='CFTC 포지션'&&s.type==='line'));
samples.news_regions=G.sphere(data('geoecon').sections.find(s=>s.type==='globe'),data('coastlines').arcs);
const entity=data('dragonglass').sections.find(s=>s.type==='entities').entities[0];samples.entity=A.line({title:entity.name+' · 3개월',left:'시작=100',date_format:'day',series:[{name:entity.name,axis:'left',points:entity.curve}]});
samples.scanner=A.scanCandles(data('multiasset').sections.find(s=>s.type==='scanner').items[0]);
samples.allocation=A.line(data('multiasset').sections.find(s=>s.type==='allocation').chart);
const ml=data('ml'),mlTarget=ml.sections.find(s=>s.type==='ml');
samples.ml_long=A.line(mlTarget.charts[0]);samples.ml_recent=A.line(mlTarget.charts[1]);
samples.ml_composite=A.line(ml.sections.find(s=>s.type==='line'&&s.group==='전망 요약'));
samples.ml_lag=A.lagCorrelation(ml.sections.find(s=>s.type==='lagcorrelation'));
samples.ml_models=A.modelLeaderboard({panels:[ml.sections.find(s=>s.type==='modelleaderboard').panels[0]]});
samples.ml_features=A.featureSelection(ml.sections.find(s=>s.type==='featureselection').panels[1]);
samples.ml_shap=A.shap(ml.sections.find(s=>s.type==='shap'));
const maxGroup=data('maximus').sections.find(s=>s.type==='moe'&&s.group==='지수');samples.maximus_fan=A.moeFan(maxGroup.cards[0]);samples.maximus_topology=A.moeTopology(maxGroup.cards);
const N=ctx.window.ResearchNotes,topics=N.topics(N.seeds(data('principium').sections.find(s=>s.type==='notebook')));samples.research_cloud=N.cloud(topics);samples.research_topics=N.graph(topics);
const iw=data('iw').sections.find(s=>s.type==='reviewcharts');samples.iw_states=A.stateTimeline(iw.latest[0]);samples.iw_archive_states=A.stateTimeline(iw.archives.at(-1).charts[0]);samples.iw_archive_ml=A.line(iw.archives.at(-1).charts[1]);
const ask=data('ask_digest');for(const [i,r] of ask.sections.find(s=>s.type==='digestcharts').items.entries())samples['digest_key_'+i]=A.line(r.chart);samples.digest_long=ctx.window.ResearchCharts.bars(ask.sections.find(s=>s.type==='digesttrends').panels[2].rows,{unit:'%',title:'2년 관측 수익률'});
const relation=data('dragonglass').sections.find(s=>s.type==='relationlab');samples.relation_graph=ctx.window.RelationViews.graphSVG(relation,{node:'stock:NVDA'});samples.relation_positive=ctx.window.ResearchCharts.bars(Object.entries(relation.scenarios[4].impacts).filter(([id,r])=>id.startsWith('stock:')&&r.value>=.06).map(([id,r])=>({name:relation.nodes.find(n=>n.id===id).name,value:r.value})),{unit:'상대 강도',valueUnit:'',digits:3,title:'HBM 사이클 가속 · 양의 영향'});samples.relation_negative=ctx.window.ResearchCharts.bars(Object.entries(relation.scenarios[2].impacts).filter(([id,r])=>id.startsWith('stock:')&&r.value<=-.06).map(([id,r])=>({name:relation.nodes.find(n=>n.id===id).name,value:r.value})),{unit:'상대 강도',valueUnit:'',digits:3,title:'TSMC 공급 차질 · 음의 영향'});
const geo=data('geoecon'),geoC=ctx.window.GeoViews;for(const p of geo.sections.find(s=>s.type==='geocomposites').panels)samples['geo_'+p.id]=A.line(p.chart);const gp=geo.sections.find(s=>s.type==='geogpr');geoC.gprCharts(gp).forEach((c,i)=>samples['geo_gpr_'+i]=A.line(c));const kw=geo.sections.find(s=>s.type==='geokeywords');samples.geo_keywords=A.line(geoC.keywordChart(kw.terms[0]));const ch=geo.sections.find(s=>s.type==='geochannels');samples.geo_channel=geoC.channelGraph(ch.channels[0],ch.topics);
const ov=data('overview_state');for(const p of ov.panels){samples[p.id+'_trajectory']=ctx.window.OverviewViews.hologram(p);samples[p.id+'_stacked']=ctx.window.OverviewViews.radar(p);}samples.overview_leaders=ctx.window.OverviewViews.wormhole(ov.leaders);
const earn=data('earnings'),EV=ctx.window.EarningsViews;samples.earnings_global=EV.globalBars(earn.sections.find(s=>s.type==='earningsglobal'));for(const market of ['KR','US']){const c=earn.sections.find(s=>s.type==='earningsestimates'&&s.market===market).cards.find(c=>c.symbol===(market==='KR'?'000660.KS':'NVDA'));c.metrics.forEach((m,i)=>samples['earnings_'+market+'_'+i]=EV.annualBars(m));}
const own=data('strategies').sections.find(s=>s.type==='ownership');if(own.cards[0]?.spark.length>1)samples.ownership_spark=ctx.window.OwnershipViews.spark(own.cards[0]);const of=own.cards.flatMap(c=>c.filings).find(f=>f.study?.curve?.length>2);if(of)samples.ownership_drift=A.scatter({title:'SEC 접수 후 SPY 대비',points:of.study.curve,x_label:'D0 이후 거래 관측',y_label:'SPY 대비 누적 %p',trajectory:true});
samples.scenario=ctx.window.ResearchCharts.bars(data('dragonglass').sections.find(s=>s.type==='scenario').rows.filter(r=>r.market==='KR').map(r=>({name:r.name,value:r.beta*-10})),{unit:'%',title:'시장 −10% 가정 · Beta 민감도'});
(async()=>{for(const [name,html] of Object.entries(samples)){let s=html.match(/<svg[\s\S]*<\/svg>/)?.[0];if(!s)throw Error(name+' empty');s=s.replace(/ xmlns="http:\/\/www.w3.org\/2000\/svg"/,'').replace('<svg ','<svg xmlns="http://www.w3.org/2000/svg" font-family="Malgun Gothic, sans-serif" ').replace(/(<svg[^>]*>)/,'$1'+styles);fs.writeFileSync(path.join(out,name+'.svg'),s);await sharp(Buffer.from(s)).resize({width:1100}).png().toFile(path.join(out,name+'.png'));}console.log('Rasterized',Object.keys(samples).length,'chart samples without a browser.');})().catch(e=>{console.error(e);process.exitCode=1;});
