const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');const context=vm.createContext({window:{},URL});for(const file of ['company-news','topic-news'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../docs/'+file+'.js'),'utf8'),context);const T=context.window.TopicNews,empty={items:[],count:0,tone_summary:{available:false}},topic={id:'fed',name:'연준',kind:'policy',query:'<script>bad</script>',title_groups:[['Fed']],data_available:false,available:false,sets:{gdelt:empty,local:empty}},section={start:'2026-09-04',end:'2026-09-10',collection:{status:'access_refused',attempted_at:'2026-09-11T05:00:00Z'}};let h=T.detail(topic,'gdelt',section);assert(h.includes('관측 수 —'));assert(h.includes('검색 결과를 아직 확보하지 못했습니다'));assert(!h.includes('관측 0건'));assert(!h.includes('<script>'));assert(h.includes('&lt;script&gt;'));h=T.detail(topic,'local',section);assert(h.includes('관측 0건'));assert(h.includes('기존 기업·정책 RSS'));h=T.detail({...topic,data_available:true,available:true,capped:true},'gdelt',section);assert(h.includes('관측 0건'));assert(h.includes('반환 상한250개'));h=T.articles([{id:'a',title:'<img src=x>',url:'javascript:alert(1)',time:'2026-09-09',time_basis:'RSS 발행',matched_terms:['<unsafe>'],tone:{available:false,reason:'미확보'}}]);assert(!h.includes('href="javascript:'));assert(!h.includes('<img'));assert(h.includes('&lt;unsafe&gt;'));console.log('PASS topic news: unavailable versus zero, cached/search distinction, provider cap and escaping');
// A batch-level failure must not invent a request time for an unrequested topic.
h=T.detail({...topic,error:'collection_aborted',abort_reason:'HTTPError',abort_http_status:429,deferred_at:'2026-09-13T01:00:00Z',url:'https://api.gdeltproject.org/api/v2/doc/doc?query=test&mode=artlist'},'gdelt',section);
assert(h.includes('배치 중단으로 조회 보류'));assert(h.includes('HTTP 429'));
assert(h.includes('최근 실제 시도 미확보'));assert(!h.includes(section.collection.attempted_at));
assert(h.includes('보류 시각 2026-09-13T01:00:00Z'));
assert(h.includes('href="https://api.gdeltproject.org/api/v2/doc/doc?query=test&amp;mode=artlist"'));
h=T.detail({...topic,data_available:true,available:true,retrieved_at:'2026-09-13T00:00:00Z',checked_at:'2026-09-13T00:00:00Z'},'gdelt',section);
assert(h.includes('성공 조회 자료 보존'));assert(!h.includes('access_refused'));
console.log('PASS topic news: deferred versus attempted timestamps, cause, source query and preserved success');
