'use strict';
const assert=require('node:assert/strict');
module.exports=(context,data)=>{
 const T=context.window.TradeViews,s=data.globe.sections.find(s=>s.type==='tradeglobe');
 assert(s&&s.areas.length===45);assert.equal(s.year,Number(data.globe.as_of.slice(0,4))-2);
 const st={area:'KR',direction:'out',query:'',sort:'desc',limit:'20',partner:'',lon:128,lat:36,zoom:1};
 const rows=T.flows(s,st),us=rows.find(r=>r.to.id==='US'),kr=s.areas.find(a=>a.id==='KR');
 assert.equal(rows.length,44);assert.equal(us.from.id,'KR');assert.equal(us.share,Number(us.usd)/Number(kr.world_usd)*100);
 const incoming=T.flows(s,{...st,direction:'in'}).find(r=>r.from.id==='US');
 assert.equal(incoming.to.id,'KR');assert.notEqual(incoming.usd,us.usd);
 const html=T.map(s,st,data.coastlines.arcs);assert(!/NaN|Infinity|undefined/.test(html));
 assert.equal((html.match(/data-trade-arc=/g)||[]).length,20);assert(html.includes('data-trade-arrow'));
 assert.equal((T.map(s,{...st,partner:'US'}).match(/data-trade-arc=/g)||[]).length,1);
 assert(T.map(s,{...st,direction:'in',partner:'US'}).includes('data-trade-arc="US&gt;KR"'));
 const missing=JSON.parse(JSON.stringify(s));Object.assign(missing.areas.find(a=>a.id==='RU'),{exports:[],world_usd:null});
 assert.equal((T.map(missing,{...st,area:'RU'}).match(/data-trade-arc=/g)||[]).length,0);
 assert(T.width('1000000000')<T.width('100000000000'));assert(T.width('1000000000000000000')<=4.8);
 assert.equal(T.exact('1234567890123.12345'),'1,234,567,890,123.12345');assert.equal(T.exact(null),'미확보');
 const path=T.greatCircle(kr,s.areas.find(a=>a.id==='US'));assert.equal(path.length,81);
 assert(Math.abs(path[0][0]-128)<1e-8);assert(Math.abs(path.at(-1)[0]+98)<1e-8);
 assert.equal(T.greatCircle(kr,kr).length,0);
 const panel=T.detail(s,{...st,partner:'US'});assert(panel.includes(T.exact(us.usd)));assert(panel.includes('reporterCode=410'));
 assert(panel.includes('집계 플래그'));assert(T.detail(missing,{...st,area:'RU',partner:'US'}).includes('관측값이 없습니다'));
 const bad=JSON.parse(JSON.stringify(s));bad.areas[0].name='<img src=x onerror=alert(1)>';
 assert(!T.render(bad,0).includes('<img'));assert(T.render(bad,0).includes('&lt;img'));
 const asc=T.flows(s,{...st,sort:'asc'}).filter(r=>r.usd!=null);assert(Number(asc[0].usd)<=Number(asc.at(-1).usd));
 assert.equal(T.flows(s,{...st,query:'ZZZ_NOT_A_COUNTRY'}).length,0);
 assert.equal(T.flows(s,{...st,query:'842'})[0].partner.id,'US');
 console.log('PASS: annual trade direction, denominator, missing/zero, geodesic, widths, exact USD and escaping.');
};
