'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),{parse}=require('./test_dom_stub.cjs');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),data=JSON.parse(read('docs/data/overview_state.json'));
function context(){let requests=0,resolve;const frames=new Map();let fid=0;const ctx=vm.createContext({window:{requestAnimationFrame:f=>{frames.set(++fid,f);return fid;},cancelAnimationFrame:id=>frames.delete(id),fetch:()=>{requests++;return new Promise(r=>{resolve=()=>r({ok:true,json:async()=>data});});}}});
 for(const n of ['charts','analysis-charts','overview-views'])vm.runInContext(read('docs/'+n+'.js'),ctx);return {V:ctx.window.OverviewViews,frames,requests:()=>requests,resolve:()=>resolve(),ctx};}
async function checks(){
 const {V,frames}=context(),p=data.panels[0],crowd=data.panels[1];
 for(const a of data.panels){const h=V.hologram(a),r=V.radar(a);assert.equal((h.match(/data-state-quadrant=/g)||[]).length,4);assert.equal((h.match(/data-state-date=/g)||[]).length,36);assert.equal((r.match(/data-stacked-date=/g)||[]).length,4);assert.equal((r.match(/data-radar-wall=/g)||[]).length,a.axes.length*3);assert(!/NaN|undefined|Infinity/.test(h+r));}
 // Axis domains must enclose every observation and zero; real small ranges must fill the frame.
 for(const panel of data.panels){const before=JSON.stringify(panel),roles=Object.fromEntries(panel.axes.map(a=>[a.role,a.key])),domains=V.spatialDomain(panel);
  ['x','z','y'].forEach((role,i)=>{const values=panel.rows.map(r=>r.z[roles[role]]).filter(Number.isFinite),[lo,hi]=domains[i];assert(lo<Math.min(0,...values)&&hi>Math.max(0,...values),'no axis clipping');assert((Math.max(...values)-Math.min(...values))/(hi-lo)>.65,'actual observations occupy most of each axis');});
  assert.equal((V.hologram(panel).match(/data-state-tick=/g)||[]).length,15,'numeric ticks on all three axes');assert.equal(JSON.stringify(panel),before,'display fitting cannot mutate source data');
  for(const label of V.hologram(panel).matchAll(/<text[^>]* x="([^"]+)" y="([^"]+)"/g)){assert(+label[1]>=0&&+label[1]<=1100&&+label[2]>=18&&+label[2]<=706,'default view retains every axis label inside the stage');}
 }
 const extreme=structuredClone(p);extreme.rows[0].z.growth=8;extreme.rows[1].z.growth=12;assert(V.spatialDomain(extreme)[0][1]>12,'outliers are retained instead of clipped at the former 2.2z boundary');
 const flat=structuredClone(p);for(const row of flat.rows)for(const key of Object.keys(row.z))row.z[key]=0;assert(!/NaN|undefined|Infinity/.test(V.hologram(flat)),'constant axes remain finite');
 assert.equal((V.hologram(p).match(/data-state-halo=/g)||[]).length,36);assert.equal((V.hologram(crowd).match(/data-state-halo=/g)||[]).length,0);
 const missing=structuredClone(p);missing.rows[15].z.growth=null;assert.equal((V.hologram(missing).match(/data-state-segment=/g)||[]).length,33,'missing point breaks both adjacent lines');missing.milestones[0].z.profits=null;assert.equal((V.radar(missing).match(/data-stacked-date=/g)||[]).length,3,'no zero filled radar');
 const leaderBefore=JSON.stringify(data.leaders);for(const angle of [0,.3,1,2]){const leaders=V.wormhole(data.leaders,angle);assert.equal((leaders.match(/data-worm-symbol=/g)||[]).length,10);assert.equal((leaders.match(/data-leader-terrace=/g)||[]).length,5);assert(!leaders.includes('<circle'),'leaders use plate markers');assert(!/NaN|Infinity|undefined/.test(leaders));}assert.equal(JSON.stringify(data.leaders),leaderBefore);
 const html=V.view(data);assert(!html.includes('type="range"'),'direct manipulation replaces camera sliders');assert(V.hologram(p).includes('data-glass-plate'),'glass spatial plane');assert.equal((V.hologram(p).match(/class="state-volume"/g)||[]).length,1,'bounded 3D volume');assert.equal((html.match(/data-state-jump=/g)||[]).length,8,'four accessible date controls per panel');assert(V.radar(p).includes('radar-glass-'),'date-specific glass layers');assert(!/NaN|undefined|Infinity/.test(html));const unsafe=structuredClone(data);unsafe.leaders.stocks[0].name='<script>alert(1)</script>';assert(!V.view(unsafe).includes('<script>'));assert(V.view(unsafe).includes('&lt;script&gt;'));
 const c=parse(html);V.bind(c,data);const panels=c.querySelectorAll('[data-coordinate]');assert.equal(panels.length,2);
 for(const panel of panels){const slider=panel.querySelector('[data-state-yaw]'),graph=panel.querySelector('[data-state-holo]'),before=graph.innerHTML;slider.value='120';await slider.fire('input');assert.notEqual(graph.innerHTML,before);
  graph.events.pointerdown[0]({clientX:0});graph.events.pointermove[0]({clientX:30});graph.events.pointerup[0]({});for(const [id,fn] of [...frames]){frames.delete(id);fn();}await panel.querySelector('[data-state-reset]').fire('click');assert.equal(slider.value,'60');assert.equal(graph.innerHTML,before);
  await panel.querySelector('[data-state-spin]').fire('click');}
 assert.equal(frames.size,2);const worm=panels[1].querySelector('[data-worm-symbol]');await worm.fire('click');assert(panels[1].querySelector('[data-worm-detail]').innerHTML.includes('USD bn'));V.cancel();assert.equal(frames.size,0);
 const a=context(),first=parse('<div></div>'),second=parse('<div></div>');first.innerHTML='untouched';const one=a.V.mount(first),two=a.V.mount(second);assert.equal(a.requests(),1,'concurrent mounts share one local fetch');a.resolve();await Promise.all([one,two]);assert.equal(first.innerHTML,'untouched','stale route must not receive render');assert(second.innerHTML.includes('거시 국면'));a.V.cancel();await a.V.mount(first);assert.equal(a.requests(),1,'cached navigation');a.V.cancel();
 const b=context(),out=parse('<div></div>');out.innerHTML='preserve';const pending=b.V.mount(out);b.V.cancel();b.resolve();await pending;assert.equal(out.innerHTML,'preserve','route cancellation while loading');
 assert(read('docs/app.js').includes("OverviewViews.mount(document.querySelector('#overview-state'))"));assert(read('docs/app.js').includes('ResearchDashboard.cancel();OverviewViews.cancel();'));
 const motion=context(),surface=parse('<div><svg viewBox="0 0 800 500"></svg></div>');let cameraState={yaw:0,pitch:.3,zoom:1};
 const camera=motion.ctx.window.AnalysisCharts.bindCamera(surface,{read:()=>cameraState,write:v=>{cameraState=v;},draw:()=>{},reset:()=>{cameraState={yaw:0,pitch:.3,zoom:1};}});
 const gesture=()=>{surface.events.pointerdown[0]({clientX:0,clientY:0,pointerId:1,button:0});surface.events.pointermove[0]({clientX:50,clientY:20,pointerId:1});surface.events.pointerup[0]({type:'pointerup',pointerId:1});};
 gesture();assert.equal(motion.frames.size,2,'render and damped orbit scheduled');const released=cameraState.yaw;for(const [id,fn] of [...motion.frames]){motion.frames.delete(id);fn();}assert(cameraState.yaw>released,'orbit decays after release');
 surface.events.blur[0]();for(const [id,fn] of [...motion.frames]){motion.frames.delete(id);fn();}assert.equal(motion.frames.size,0,'blur stops continued movement');camera.reset();assert.equal(cameraState.yaw,0);
 motion.ctx.window.matchMedia=()=>({matches:true});gesture();assert.equal(motion.frames.size,1,'reduced motion draws without inertia');camera.dispose();assert.equal(motion.frames.size,0,'dispose cancels remaining frame');
 console.log('Overview6/5 axes, four stacked milestones, trajectory gaps, source dates, rotation/leader selection, frame cleanup and fetch race tests passed.');
}
module.exports=checks();module.exports.catch(e=>{console.error(e);process.exitCode=1;});
