'use strict';
const assert=require('node:assert/strict');
const C=require('../docs/charts.js');
const sample={points:[['2025-01-01',-1],['2025-02-01',2],['2025-03-01',0]],start:'2025-01-01',end:'2025-03-01'};
const rs=C.line(sample,{kind:'rs',title:'<script>bad</script>'});
assert.equal((rs.match(/data-guide=/g)||[]).length,5);
assert(rs.includes('data-band="-2:2"'));
assert.equal((rs.match(/data-price-series=/g)||[]).length,1);
assert(!rs.includes('<script>'));
assert(rs.includes('role="img"'));
const mom=C.line(sample,{kind:'momentum'});
assert.equal((mom.match(/data-guide=/g)||[]).length,1);
assert(mom.includes('data-area="positive"')&&mom.includes('data-area="negative"'));
assert(mom.includes('누적 초과수익률 (%)'));
assert(!mom.includes('NaN')&&!mom.includes('Infinity'));
assert(C.line({points:[]}).includes('chart-empty'));
const bars=C.bars([{name:'a',value:-2},{name:'b',value:1},{name:'missing',value:null}],{markers:[-2.58,-1,1,2.58]});
assert.equal((bars.match(/data-bar-value=/g)||[]).length,2);
assert.equal((bars.match(/data-bar-guide=/g)||[]).length,5);
const hm=C.heatmap([{name:'a',group:'KR',values:[null,3]}],['%p','σ'],'units');
assert(hm.includes('—')&&!hm.includes('NaN')&&hm.includes('σ'));
console.log('PASS: RS guides, single series, momentum positive/negative areas, units, missing data and escaping.');
